services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx/dev
      args:
        - HOST_UID=${DOCKER_UID:-1000}
        - HOST_GID=${DOCKER_GID:-1000}
    ports:
      - "80:8080"
    volumes:
      - ./backend/public:/var/www/html/public/
    links:
      - php-fpm
    networks:
      - php-devops-test
    restart: no

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm/dev
      args:
        - HOST_UID=${DOCKER_UID:-1000}
        - HOST_GID=${DOCKER_GID:-1000}
    volumes:
      - ./backend:/var/www/html/
    networks:
      - php-devops-test
    restart: no

networks:
  php-devops-test:
    name: php-devops-test
    driver: bridge
